language: node_js
node_js:
  - "10.16"

before_install:
  - npm i -g npm@6.9.0

branches:
  only:
  - master

script:
  - rm -rf public
  - gatsby build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: './public'
  keep_history: true
  on:
    branch: master